### ISSUE TITLE
AppImage missing

### ISSUE THREAD

**Issue by probonopd** [Stellarium/stellarium#1288]
### Expected Behaviour

An AppImage is available for download

### Actual Behaviour

> Important note: We discontinued support an AppImage builds since version 0.20.3 due technical problems of AppImage architecture! 

### Additional information

Please describe the "technical problems of AppImage architecture" so that we can fix them. cc @azubieta

Snaps are not a viable alternative since they are not one file = one app that can run on most Linux distributions without installation, and can not easily added to long-term archival storage in the same way an AppImage can.

**Comment by gzotti** [comment]
There were issues around SSH libraries.

**Comment by alex-w** [comment]
Not SSH, but OpenSSL

**Comment by probonopd** [comment]
@azubieta I belive you have nailed those, haven't you?

**Comment by azubieta** [comment]
This issue is well known and it's also fixed. The reason is that app built using OpenSSL 1.1 or greater are not compatible with with system that ship OpenSSL 1.0 (some features are missing as you may imagine). The solution is to ship OpenSSL into the AppImage. But as OpenSSL is a critical piece of code only the very latest version should be included.

To do so you must use [appimage-builder](https://appimage-builder.readthedocs.io/) or other solution that allows to build AppImages using a recent system while keeping the backward compatibility.

**Comment by probonopd** [comment]
@gzotti would you like a PR that would build Stellarium with appimage-builder?

**Comment by gzotti** [comment]
I have no detailed knowledge about AppImage, sorry. If a PR makes AppImages reliably accessible again, easily, @alex-w will hopefully like it. Alexander?

**Comment by probonopd** [comment]
Yes, it would make it much more reliable by bundling _everything_.

**Comment by azubieta** [comment]
Making an AppImage of stellarium was really simple. Bellow you will find the recipe for appimage-builder.

All you have to to is to adjust the script section to your CI setup and properly set the version.

Useful links:
- [appimage-builder documentation](https://appimage-builder.readthedocs.io)
- [environment variables in recipe files](https://appimage-builder.readthedocs.io/en/latest/reference/version_1.html#environment-variables)


```yml
version: 1

script:
    - rm -rf AppDir || true
    - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
    - make
    - make install DESTDIR=AppDir

AppDir:
  path: ./AppDir

  app_info:
    id: stellarium
    name: Stellarium
    icon: stellarium
    version: latest
    exec: usr/bin/stellarium

  apt:
    arch: amd64
    sources:
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse'
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse'

    include:
      - libqt5core5a
      - libqt5gui5
      - libqt5multimedia5
      - libqt5multimediawidgets5
      - libqt5network5
      - libqt5positioning5
      - libqt5printsupport5
      - libqt5script5
      - libqt5serialport5
      - libqt5widgets5
    exclude: []

  files:
    exclude:
      - usr/lib/x86_64-linux-gnu/gconv
      - usr/share/man
      - usr/share/doc/*/README.*
      - usr/share/doc/*/changelog.*
      - usr/share/doc/*/NEWS.*
      - usr/share/doc/*/TODO.*
  runtime:
    env:
      APPDIR_LIBRARY_PATH: $APPDIR/lib/x86_64-linux-gnu:$APPDIR/usr/lib/x86_64-linux-gnu:$APPDIR/usr/lib/x86_64-linux-gnu/pulseaudio

  test:
    debian:
      image: appimagecrafters/tests-env:debian-stable
      command: "./AppRun"
      use_host_x: True
    centos:
      image: appimagecrafters/tests-env:centos-7
      command: "./AppRun"
      use_host_x: True
    arch:
      image: appimagecrafters/tests-env:archlinux-latest
      command: "./AppRun"
      use_host_x: True
    fedora:
      image: appimagecrafters/tests-env:fedora-30
      command: "./AppRun"
      use_host_x: True
    ubuntu:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: "./AppRun"
      use_host_x: True


AppImage:
  update-information: None
  sign-key: None
  arch: x86_64

```
